/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formulários;

import java.sql.*;
import Classes.*;

/**
 *
 * @author Mr. Wanny
 */
public class FormularioSobre extends javax.swing.JFrame {

    /**
     * Creates new form FormularioSobre
     */
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    public FormularioSobre() {
        initComponents();
        con = SQL.connect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelSobre = new javax.swing.JPanel();
        lblImagem = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblLogotipo = new javax.swing.JLabel();
        PainelInformacoes = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();

        setTitle("Sobre");
        setResizable(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        getContentPane().setLayout(null);

        PainelSobre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        PainelSobre.setLayout(null);

        lblImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/login.png"))); // NOI18N
        PainelSobre.add(lblImagem);
        lblImagem.setBounds(30, 20, 150, 170);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("aos mais complexos.");
        PainelSobre.add(jLabel2);
        jLabel2.setBounds(140, 170, 430, 22);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("A Gingue Tech é uma Empresa voltada no ramo de");
        PainelSobre.add(jLabel3);
        jLabel3.setBounds(140, 50, 420, 22);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Prestação de Serviços. Desde 2020 que temos para si");
        PainelSobre.add(jLabel4);
        jLabel4.setBounds(140, 80, 430, 22);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("a Qualidade e a Eficiência que so a Gingue Tech");
        PainelSobre.add(jLabel5);
        jLabel5.setBounds(160, 110, 390, 22);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("pode oferecer, desde os serviços mais simples até");
        PainelSobre.add(jLabel6);
        jLabel6.setBounds(160, 140, 400, 22);

        getContentPane().add(PainelSobre);
        PainelSobre.setBounds(20, 90, 610, 220);

        lblLogotipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Gingue Tech 2.0.png"))); // NOI18N
        lblLogotipo.setText("jLabel1");
        getContentPane().add(lblLogotipo);
        lblLogotipo.setBounds(330, 10, 360, 80);

        PainelInformacoes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        PainelInformacoes.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Versão");
        PainelInformacoes.add(jLabel7);
        jLabel7.setBounds(30, 160, 70, 22);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Plataforma");
        PainelInformacoes.add(jLabel9);
        jLabel9.setBounds(290, 160, 110, 22);

        jCheckBox2.setText("Web");
        jCheckBox2.setToolTipText("Web");
        jCheckBox2.setEnabled(false);
        PainelInformacoes.add(jCheckBox2);
        jCheckBox2.setBounds(300, 190, 47, 23);

        jCheckBox3.setSelected(true);
        jCheckBox3.setText("Desktop");
        jCheckBox3.setToolTipText("Desktop");
        jCheckBox3.setEnabled(false);
        PainelInformacoes.add(jCheckBox3);
        jCheckBox3.setBounds(360, 190, 65, 23);

        jCheckBox4.setText("Android");
        jCheckBox4.setToolTipText("Android");
        jCheckBox4.setEnabled(false);
        PainelInformacoes.add(jCheckBox4);
        jCheckBox4.setBounds(430, 190, 63, 23);

        jCheckBox1.setText("iOS");
        jCheckBox1.setToolTipText("iOS");
        jCheckBox1.setEnabled(false);
        PainelInformacoes.add(jCheckBox1);
        jCheckBox1.setBounds(500, 190, 41, 23);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/help.png"))); // NOI18N
        jLabel10.setText("(+244) 931 698 904");
        PainelInformacoes.add(jLabel10);
        jLabel10.setBounds(340, 270, 140, 40);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/twitter.png"))); // NOI18N
        jLabel11.setText("helmanvemba83@gmail.com");
        PainelInformacoes.add(jLabel11);
        jLabel11.setBounds(160, 270, 170, 40);

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Gjhrhb7r0lb.png"))); // NOI18N
        jLabel12.setText("Gingue Tech");
        PainelInformacoes.add(jLabel12);
        jLabel12.setBounds(60, 270, 90, 40);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Contacto do Desenvolvedor");
        PainelInformacoes.add(jLabel13);
        jLabel13.setBounds(30, 240, 250, 22);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Sistema de Gestão Empresarial");
        jLabel14.setToolTipText("Título");
        PainelInformacoes.add(jLabel14);
        jLabel14.setBounds(0, 20, 610, 50);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Gingue Soft Enterprise");
        jLabel15.setToolTipText("Sub - Título");
        PainelInformacoes.add(jLabel15);
        jLabel15.setBounds(0, 70, 610, 40);

        jRadioButton1.setSelected(true);
        jRadioButton1.setText("v1.0.0");
        jRadioButton1.setEnabled(false);
        PainelInformacoes.add(jRadioButton1);
        jRadioButton1.setBounds(40, 190, 57, 23);

        getContentPane().add(PainelInformacoes);
        PainelInformacoes.setBounds(20, 320, 610, 330);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/gnu.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(540, 30, 540, 640);

        setSize(new java.awt.Dimension(1081, 757));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_formMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioSobre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioSobre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioSobre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioSobre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioSobre().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelInformacoes;
    private javax.swing.JPanel PainelSobre;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JLabel lblImagem;
    private javax.swing.JLabel lblLogotipo;
    // End of variables declaration//GEN-END:variables
}
