/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formulários;

import java.sql.*;
import javax.swing.*;
import Classes.SQL;
import java.util.*;
import net.proteanit.sql.DbUtils;
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.view.*;

/**
 *
 * @author Mr. Wanny
 */
public class FormularioServico extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormularioServico
     */
    public FormularioServico() {
        initComponents();
        con = SQL.connect();
    }

    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    private String tipo;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        PainelServico = new javax.swing.JPanel();
        PainelEmissao = new javax.swing.JPanel();
        lblOS = new javax.swing.JLabel();
        txtOS = new javax.swing.JTextField();
        lblData = new javax.swing.JLabel();
        txtData = new javax.swing.JTextField();
        rbtOrcamento = new javax.swing.JRadioButton();
        rbtServico = new javax.swing.JRadioButton();
        PainelCliente = new javax.swing.JPanel();
        txtCliente = new javax.swing.JTextField();
        lblCliente = new javax.swing.JLabel();
        txtNomeCliente = new javax.swing.JTextField();
        lblID = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_Cliente = new javax.swing.JTable();
        lblSituacao = new javax.swing.JLabel();
        cboSituacao = new javax.swing.JComboBox<>();
        PainelTecnico = new javax.swing.JPanel();
        txtTecnico = new javax.swing.JTextField();
        lblTecnico = new javax.swing.JLabel();
        lblidTecnico = new javax.swing.JLabel();
        txtNomeTecnico = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_Tecnico = new javax.swing.JTable();
        lblPrecoUnitario = new javax.swing.JLabel();
        lblDescricao = new javax.swing.JLabel();
        txtDescricaoServico = new javax.swing.JTextField();
        btnAdicionar = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnApagar = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        lblQuantidade = new javax.swing.JLabel();
        txtQuantidade = new javax.swing.JTextField();
        lblDesconto = new javax.swing.JLabel();
        txtDesconto = new javax.swing.JTextField();
        jspPrecoUnitario = new com.toedter.components.JSpinField();
        lblSolucao = new javax.swing.JLabel();
        txtSolucao = new javax.swing.JTextField();
        lblPrecoTotal = new javax.swing.JLabel();
        jspPrecoTotal = new com.toedter.components.JSpinField();
        lblLimpar = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Emissão de Serviço");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Emissão de Serviço");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(350, 0, 310, 48);

        PainelServico.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        PainelServico.setLayout(null);

        PainelEmissao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        PainelEmissao.setLayout(null);

        lblOS.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblOS.setText("OS");
        PainelEmissao.add(lblOS);
        lblOS.setBounds(20, 20, 30, 40);

        txtOS.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtOS.setEnabled(false);
        PainelEmissao.add(txtOS);
        txtOS.setBounds(50, 20, 70, 40);

        lblData.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblData.setText("Data");
        PainelEmissao.add(lblData);
        lblData.setBounds(130, 20, 160, 40);

        txtData.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtData.setEnabled(false);
        PainelEmissao.add(txtData);
        txtData.setBounds(180, 20, 260, 40);

        buttonGroup1.add(rbtOrcamento);
        rbtOrcamento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rbtOrcamento.setText("Orçamento");
        rbtOrcamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtOrcamentoActionPerformed(evt);
            }
        });
        PainelEmissao.add(rbtOrcamento);
        rbtOrcamento.setBounds(60, 70, 115, 33);

        buttonGroup1.add(rbtServico);
        rbtServico.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rbtServico.setText("Serviço");
        rbtServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtServicoActionPerformed(evt);
            }
        });
        PainelEmissao.add(rbtServico);
        rbtServico.setBounds(230, 70, 83, 33);

        PainelServico.add(PainelEmissao);
        PainelEmissao.setBounds(20, 20, 460, 110);

        PainelCliente.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Cliente"));
        PainelCliente.setLayout(null);

        txtCliente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtClienteKeyReleased(evt);
            }
        });
        PainelCliente.add(txtCliente);
        txtCliente.setBounds(20, 20, 120, 40);

        lblCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/loupe.png"))); // NOI18N
        PainelCliente.add(lblCliente);
        lblCliente.setBounds(150, 20, 40, 40);

        txtNomeCliente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtNomeCliente.setEnabled(false);
        PainelCliente.add(txtNomeCliente);
        txtNomeCliente.setBounds(240, 20, 170, 40);

        lblID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblID.setText("Nome");
        PainelCliente.add(lblID);
        lblID.setBounds(190, 20, 50, 40);

        tb_Cliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Morada", "Telefone", "Email", "Estatus"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_Cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_ClienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_Cliente);

        PainelCliente.add(jScrollPane1);
        jScrollPane1.setBounds(20, 70, 390, 90);

        PainelServico.add(PainelCliente);
        PainelCliente.setBounds(490, 10, 430, 180);

        lblSituacao.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblSituacao.setText("Situação");
        PainelServico.add(lblSituacao);
        lblSituacao.setBounds(20, 140, 80, 30);

        cboSituacao.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cboSituacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Na Bancada", "Entrega OK", "Orçamento REPROVADO", "Aguardando Aprovação", "Aguardando Material", "Abandonado pelo Cliente", "Retornou" }));
        PainelServico.add(cboSituacao);
        cboSituacao.setBounds(100, 140, 380, 31);

        PainelTecnico.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Técnico"));
        PainelTecnico.setLayout(null);

        txtTecnico.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtTecnico.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTecnicoKeyReleased(evt);
            }
        });
        PainelTecnico.add(txtTecnico);
        txtTecnico.setBounds(20, 20, 110, 40);

        lblTecnico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/loupe.png"))); // NOI18N
        PainelTecnico.add(lblTecnico);
        lblTecnico.setBounds(140, 20, 40, 40);

        lblidTecnico.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblidTecnico.setText("Nome");
        PainelTecnico.add(lblidTecnico);
        lblidTecnico.setBounds(180, 20, 50, 40);

        txtNomeTecnico.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtNomeTecnico.setEnabled(false);
        PainelTecnico.add(txtNomeTecnico);
        txtNomeTecnico.setBounds(230, 20, 180, 40);

        tb_Tecnico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Telefone", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tb_Tecnico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_TecnicoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tb_Tecnico);

        PainelTecnico.add(jScrollPane2);
        jScrollPane2.setBounds(20, 70, 390, 70);

        PainelServico.add(PainelTecnico);
        PainelTecnico.setBounds(490, 210, 430, 150);

        lblPrecoUnitario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPrecoUnitario.setText("Preço Unitário");
        PainelServico.add(lblPrecoUnitario);
        lblPrecoUnitario.setBounds(180, 280, 120, 40);

        lblDescricao.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblDescricao.setText("Descrição");
        lblDescricao.setToolTipText("");
        PainelServico.add(lblDescricao);
        lblDescricao.setBounds(20, 180, 80, 40);

        txtDescricaoServico.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        PainelServico.add(txtDescricaoServico);
        txtDescricaoServico.setBounds(100, 180, 380, 40);

        btnAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/add.png"))); // NOI18N
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });
        PainelServico.add(btnAdicionar);
        btnAdicionar.setBounds(20, 390, 50, 50);

        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/magnifying-glass.png"))); // NOI18N
        btnPesquisar.setToolTipText("");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });
        PainelServico.add(btnPesquisar);
        btnPesquisar.setBounds(220, 390, 50, 50);

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/alterar.png"))); // NOI18N
        btnAlterar.setToolTipText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });
        PainelServico.add(btnAlterar);
        btnAlterar.setBounds(450, 390, 50, 50);

        btnApagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/remove.png"))); // NOI18N
        btnApagar.setToolTipText("Apagar");
        btnApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApagarActionPerformed(evt);
            }
        });
        PainelServico.add(btnApagar);
        btnApagar.setBounds(670, 390, 50, 50);

        btnImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/printer (1).png"))); // NOI18N
        btnImprimir.setToolTipText("Imprimir");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });
        PainelServico.add(btnImprimir);
        btnImprimir.setBounds(860, 390, 50, 50);

        lblQuantidade.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblQuantidade.setText("Quantidade");
        PainelServico.add(lblQuantidade);
        lblQuantidade.setBounds(20, 230, 100, 40);

        txtQuantidade.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtQuantidade.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtQuantidade.setText("1");
        txtQuantidade.setToolTipText("");
        PainelServico.add(txtQuantidade);
        txtQuantidade.setBounds(130, 230, 90, 40);

        lblDesconto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblDesconto.setText("Desconto");
        PainelServico.add(lblDesconto);
        lblDesconto.setBounds(20, 280, 80, 40);

        txtDesconto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtDesconto.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtDesconto.setText("0");
        txtDesconto.setToolTipText("");
        PainelServico.add(txtDesconto);
        txtDesconto.setBounds(110, 280, 60, 40);
        PainelServico.add(jspPrecoUnitario);
        jspPrecoUnitario.setBounds(300, 280, 180, 40);

        lblSolucao.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblSolucao.setText("Solução");
        PainelServico.add(lblSolucao);
        lblSolucao.setBounds(230, 230, 70, 40);

        txtSolucao.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        PainelServico.add(txtSolucao);
        txtSolucao.setBounds(300, 230, 180, 40);

        lblPrecoTotal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPrecoTotal.setText("Preço Total");
        PainelServico.add(lblPrecoTotal);
        lblPrecoTotal.setBounds(20, 330, 100, 40);
        PainelServico.add(jspPrecoTotal);
        jspPrecoTotal.setBounds(120, 330, 360, 40);

        getContentPane().add(PainelServico);
        PainelServico.setBounds(20, 50, 950, 450);

        lblLimpar.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblLimpar.setText("X");
        lblLimpar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLimparMouseClicked(evt);
            }
        });
        getContentPane().add(lblLimpar);
        lblLimpar.setBounds(940, 0, 30, 48);

        setBounds(0, 0, 1000, 560);
    }// </editor-fold>//GEN-END:initComponents

    private void txtClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClienteKeyReleased
        // TODO add your handling code here:
        String sql = "select id_cli as ID, nome_cli AS Nome, morada_cli as Morada, telefone_cli as Telefone, email_cli as Email, estatus_cli as Estatus from tb_cliente where nome_cli like ?";
        try {
            pst = con.prepareStatement(sql);
            pst.setString(1, txtCliente.getText() + "%");
            rs = pst.executeQuery();
            tb_Cliente.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Falha na Comunicação com o Banco de Dados\n" + e, "Aviso", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_txtClienteKeyReleased

    private void tb_ClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_ClienteMouseClicked
        // TODO add your handling code here:
        int setar = tb_Cliente.getSelectedRow();
        txtNomeCliente.setText(tb_Cliente.getModel().getValueAt(setar, 1).toString());
    }//GEN-LAST:event_tb_ClienteMouseClicked

    private void tb_TecnicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_TecnicoMouseClicked
        // TODO add your handling code here:
        int setar = tb_Tecnico.getSelectedRow();
        txtNomeTecnico.setText(tb_Tecnico.getModel().getValueAt(setar, 1).toString());
    }//GEN-LAST:event_tb_TecnicoMouseClicked

    private void txtTecnicoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTecnicoKeyReleased
        // TODO add your handling code here:
        String sql = "select id_tecnico as ID, nome_tecnico as Nome, telefone_tecnico as Telefone, email_tecnico as Email, estatus_tecnico as Estatus from tb_tecnico where nome_tecnico like ?";
        try {
            pst = con.prepareStatement(sql);
            pst.setString(1, txtTecnico.getText() + "%");
            rs = pst.executeQuery();
            tb_Tecnico.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Falha na Comunicação com o Banco de Dados\n" + e, "Aviso", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_txtTecnicoKeyReleased

    private void rbtOrcamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtOrcamentoActionPerformed
        // TODO add your handling code here:
        tipo = "Orcamento";
    }//GEN-LAST:event_rbtOrcamentoActionPerformed

    private void rbtServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtServicoActionPerformed
        // TODO add your handling code here:
        tipo = "Servico";
    }//GEN-LAST:event_rbtServicoActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        rbtOrcamento.setEnabled(true);
        tipo = "Orcamento";
    }//GEN-LAST:event_formInternalFrameOpened

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        // TODO add your handling code here:
        String sql = "insert into tb_os(tipo, descricao_OS, quantidade_OS, solucao_OS, situacao_OS, nome_tecnico, nome_cli, desconto, preco_unitario, preco_total)values(?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
        try {
            pst = con.prepareStatement(sql);
            pst.setString(1, tipo);
            pst.setString(2, txtDescricaoServico.getText());
            pst.setString(3, txtQuantidade.getText());
            pst.setString(4, txtSolucao.getText());
            pst.setString(5, cboSituacao.getSelectedItem().toString());
            pst.setString(6, txtNomeTecnico.getText());
            pst.setString(7, txtNomeCliente.getText());
            pst.setString(8, txtDesconto.getText());
            pst.setString(9, Integer.toString(jspPrecoUnitario.getValue()));
            pst.setString(10, Integer.toString(jspPrecoTotal.getValue()));
            if (txtNomeCliente.getText().isEmpty() || txtNomeTecnico.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Preencha os Campos!", "Aviso", JOptionPane.ERROR_MESSAGE);
            } else {
                int adicionado = pst.executeUpdate();
                if (adicionado > 0) {
                    JOptionPane.showMessageDialog(null, "Serviço Emitido com Sucesso!", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                    txtData.setText(null);
                    txtDescricaoServico.setText(null);
                    txtQuantidade.setText(null);
                    txtSolucao.setText(null);
                    cboSituacao.setSelectedItem(null);
                    txtNomeTecnico.setText(null);
                    txtNomeCliente.setText(null);
                    txtDesconto.setText("0");
                    jspPrecoUnitario.setValue(0);
                    jspPrecoTotal.setValue(0);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Falha na Comunicação com o Banco de Dados\n" + e, "Aviso", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        // TODO add your handling code here:
        String servico = JOptionPane.showInputDialog("Número Serviço");
        String sql = "select * from tb_os where id_OS = " + servico;
        try {
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            if (rs.next()) {
                txtOS.setText(rs.getString(1));
                txtData.setText(rs.getString(2));
                String rbtTipo = rs.getString(3);
                if (rbtTipo.equals("Serviço")) {
                    rbtServico.setSelected(true);
                    tipo = "Servico";
                } else {
                    rbtOrcamento.setSelected(true);
                    tipo = "Orcamento";
                }
                txtDescricaoServico.setText(rs.getString(4));
                txtQuantidade.setText(rs.getString(5));
                txtSolucao.setText(rs.getString(6));
                cboSituacao.setSelectedItem(rs.getString(7));
                txtNomeTecnico.setText(rs.getString(8));
                txtNomeCliente.setText(rs.getString(9));
                txtDesconto.setText(rs.getString(10));
                jspPrecoUnitario.setValue(Integer.parseInt(rs.getString(11)));
                jspPrecoTotal.setValue(Integer.parseInt(rs.getString(12)));
                btnAdicionar.setEnabled(false);
                btnAlterar.setEnabled(true);
                btnApagar.setEnabled(true);
            } else {
                JOptionPane.showMessageDialog(null, "Serviço não Cadastrado");
                txtOS.setText(servico);
                txtData.setText(null);
                txtDescricaoServico.setText(null);
                txtQuantidade.setText(null);
                txtSolucao.setText(null);
                cboSituacao.setSelectedItem(null);
                txtNomeTecnico.setText(null);
                txtNomeCliente.setText(null);
                txtDesconto.setText("0.00");
                jspPrecoUnitario.setValue(0);
                jspPrecoTotal.setValue(0);
                btnAdicionar.setEnabled(true);
                btnAlterar.setEnabled(true);
                btnApagar.setEnabled(true);
            }
        } catch (com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException e) {
            JOptionPane.showMessageDialog(null, "Serviço Inválido!", "Aviso", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e2) {
            JOptionPane.showMessageDialog(null, "Falha na Comunicação com o Banco de Dados\n" + e2, "Aviso", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        // TODO add your handling code here:
        String sql = "update tb_os set tipo = ?, descricao_OS = ?, quantidade_OS = ?,  solucao_OS = ?, situacao_OS = ?, nome_tecnico = ?, nome_cli = ?, desconto = ?, preco_unitario = ?, preco_total = ? where id_OS = ?";
        try {
            pst = con.prepareStatement(sql);
            pst.setString(1, tipo);
            pst.setString(2, txtDescricaoServico.getText());
            pst.setString(3, txtQuantidade.getText());
            pst.setString(4, txtSolucao.getText());
            pst.setString(5, cboSituacao.getSelectedItem().toString());
            pst.setString(6, txtNomeTecnico.getText());
            pst.setString(7, txtNomeCliente.getText());
            pst.setString(8, txtDesconto.getText());
            pst.setString(9, Integer.toString(jspPrecoUnitario.getValue()));
            pst.setString(10, Integer.toString(jspPrecoTotal.getValue()));
            pst.setString(11, txtOS.getText());
            if (txtNomeCliente.getText().isEmpty() || txtNomeTecnico.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Preencha todos Campos!", "Aviso", JOptionPane.ERROR_MESSAGE);
            } else {
                int adicionado = pst.executeUpdate();
                if (adicionado > 0) {
                    JOptionPane.showMessageDialog(null, "Serviço Alterado com Sucesso!", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                    txtData.setText(null);
                    txtDescricaoServico.setText(null);
                    txtQuantidade.setText(null);
                    txtSolucao.setText(null);
                    cboSituacao.setSelectedItem(null);
                    txtNomeTecnico.setText(null);
                    txtNomeCliente.setText(null);
                    txtDesconto.setText("0.00");
                    jspPrecoUnitario.setValue(0);
                    jspPrecoTotal.setValue(0);
                    btnAdicionar.setEnabled(true);
                    btnAlterar.setEnabled(true);
                    btnApagar.setEnabled(true);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Falha na Comunicação com o Banco de Dados\n" + e, "Aviso", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApagarActionPerformed
        // TODO add your handling code here:
        int apagar = JOptionPane.showConfirmDialog(null, "Deseja Apagar este Serviço?", "Aviso", JOptionPane.YES_NO_OPTION);
        if (apagar == JOptionPane.YES_OPTION) {
            String sql = "delete from tb_servico where id_OS = ?";
            try {
                pst = con.prepareStatement(sql);
                pst.setString(1, txtOS.getText());
                int apagado = pst.executeUpdate();
                if (txtOS.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Insira o Serviço!", "Aviso", JOptionPane.ERROR_MESSAGE);
                } else {
                    if (apagado > 0) {
                        JOptionPane.showMessageDialog(null, "Serviço Apagado com Sucesso!", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                        txtData.setText(null);
                        txtDescricaoServico.setText(null);
                        txtQuantidade.setText(null);
                        txtSolucao.setText(null);
                        cboSituacao.setSelectedItem(null);
                        txtNomeTecnico.setText(null);
                        txtNomeCliente.setText(null);
                        txtDesconto.setText("0.00");
                        jspPrecoUnitario.setValue(0);
                        jspPrecoTotal.setValue(0);
                        btnAdicionar.setEnabled(true);
                        btnAlterar.setEnabled(true);
                        btnApagar.setEnabled(true);
                    }
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Falha na Comunicação com o Banco de Dados\n" + e, "Aviso", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnApagarActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        // TODO add your handling code here:
        int confirmar = JOptionPane.showConfirmDialog(null, "Confirma a Impressão este Serviço?", "Aviso", JOptionPane.YES_NO_OPTION);
        if (confirmar == JOptionPane.YES_OPTION) {
            try {
                HashMap filtro = new HashMap();
                filtro.put("Serviço", Integer.parseInt(txtOS.getText()));
                JasperPrint print = JasperFillManager.fillReport("C:\\Users\\Mr. Wanny\\Documents\\NetBeansProjects\\Empresa Gingue Tech\\src\\Relatórios\\RelatorioFatura.jasper", filtro, con);
                JasperViewer.viewReport(print, false);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Falha na Comunicação com o Banco de Dados\n" + e, "Aviso", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnImprimirActionPerformed

    private void lblLimparMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLimparMouseClicked
        // TODO add your handling code here:
        txtOS.setText(null);
        txtData.setText(null);
        txtDescricaoServico.setText(null);
        txtQuantidade.setText(null);
        txtSolucao.setText(null);
        cboSituacao.setSelectedItem(null);
        txtNomeTecnico.setText(null);
        txtNomeCliente.setText(null);
        txtDesconto.setText("0.00");
        jspPrecoUnitario.setValue(0);
        jspPrecoTotal.setValue(0);
        btnAdicionar.setEnabled(true);
        btnAlterar.setEnabled(true);
        btnApagar.setEnabled(true);
    }//GEN-LAST:event_lblLimparMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JPanel PainelCliente;
    public static javax.swing.JPanel PainelEmissao;
    public static javax.swing.JPanel PainelServico;
    public static javax.swing.JPanel PainelTecnico;
    public static javax.swing.JButton btnAdicionar;
    public static javax.swing.JButton btnAlterar;
    public static javax.swing.JButton btnApagar;
    public static javax.swing.JButton btnImprimir;
    public static javax.swing.JButton btnPesquisar;
    public static javax.swing.ButtonGroup buttonGroup1;
    public static javax.swing.JComboBox<String> cboSituacao;
    public static javax.swing.JLabel jLabel1;
    public static javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JScrollPane jScrollPane2;
    public static com.toedter.components.JSpinField jspPrecoTotal;
    public static com.toedter.components.JSpinField jspPrecoUnitario;
    public static javax.swing.JLabel lblCliente;
    public static javax.swing.JLabel lblData;
    public static javax.swing.JLabel lblDesconto;
    public static javax.swing.JLabel lblDescricao;
    public static javax.swing.JLabel lblID;
    public static javax.swing.JLabel lblLimpar;
    public static javax.swing.JLabel lblOS;
    public static javax.swing.JLabel lblPrecoTotal;
    public static javax.swing.JLabel lblPrecoUnitario;
    public static javax.swing.JLabel lblQuantidade;
    public static javax.swing.JLabel lblSituacao;
    public static javax.swing.JLabel lblSolucao;
    public static javax.swing.JLabel lblTecnico;
    public static javax.swing.JLabel lblidTecnico;
    public static javax.swing.JRadioButton rbtOrcamento;
    public static javax.swing.JRadioButton rbtServico;
    public static javax.swing.JTable tb_Cliente;
    public static javax.swing.JTable tb_Tecnico;
    public static javax.swing.JTextField txtCliente;
    public static javax.swing.JTextField txtData;
    public static javax.swing.JTextField txtDesconto;
    public static javax.swing.JTextField txtDescricaoServico;
    public static javax.swing.JTextField txtNomeCliente;
    public static javax.swing.JTextField txtNomeTecnico;
    public static javax.swing.JTextField txtOS;
    public static javax.swing.JTextField txtQuantidade;
    public static javax.swing.JTextField txtSolucao;
    public static javax.swing.JTextField txtTecnico;
    // End of variables declaration//GEN-END:variables
}
