/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formulários;

import java.sql.*;
import javax.swing.*;
import Classes.*;
import net.proteanit.sql.DbUtils;
import javax.swing.filechooser.*;

/**
 *
 * @author Mr. Wanny
 */
public class FormularioCadastroLogin extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormularioCadastroLogin
     */
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    JFileChooser chooser;
    FileNameExtensionFilter filtro;

    public FormularioCadastroLogin() {
        initComponents();
        con = SQL.connect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLimpar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        PainelLogin = new javax.swing.JPanel();
        txtID = new javax.swing.JTextField();
        txtSenha = new javax.swing.JTextField();
        lblSenha = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        lblPerfil = new javax.swing.JLabel();
        txtPerfil = new javax.swing.JTextField();
        lblEstatus = new javax.swing.JLabel();
        txtEstatus = new javax.swing.JTextField();
        btnAdicionar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnApagar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_Login = new javax.swing.JTable();
        txtPesquisar = new javax.swing.JTextField();
        lblPesquisar = new javax.swing.JLabel();
        txtLogin = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();

        getContentPane().setLayout(null);

        lblLimpar.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblLimpar.setText("X");
        lblLimpar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLimparMouseClicked(evt);
            }
        });
        getContentPane().add(lblLimpar);
        lblLimpar.setBounds(940, 0, 30, 48);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cadastro de Login");
        jLabel1.setToolTipText("Cadastro de Login");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(340, 0, 340, 48);

        PainelLogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        PainelLogin.setLayout(null);

        txtID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtID.setEnabled(false);
        PainelLogin.add(txtID);
        txtID.setBounds(40, 10, 60, 40);

        txtSenha.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        PainelLogin.add(txtSenha);
        txtSenha.setBounds(80, 230, 850, 40);

        lblSenha.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblSenha.setText("Senha");
        PainelLogin.add(lblSenha);
        lblSenha.setBounds(10, 230, 50, 40);

        lblID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblID.setText("ID");
        PainelLogin.add(lblID);
        lblID.setBounds(10, 10, 18, 40);

        lblPerfil.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPerfil.setText("Perfil");
        PainelLogin.add(lblPerfil);
        lblPerfil.setBounds(10, 280, 50, 40);

        txtPerfil.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        PainelLogin.add(txtPerfil);
        txtPerfil.setBounds(80, 280, 850, 40);

        lblEstatus.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblEstatus.setText("Estatus");
        PainelLogin.add(lblEstatus);
        lblEstatus.setBounds(10, 330, 60, 40);

        txtEstatus.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        PainelLogin.add(txtEstatus);
        txtEstatus.setBounds(80, 330, 850, 40);

        btnAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/add.png"))); // NOI18N
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });
        PainelLogin.add(btnAdicionar);
        btnAdicionar.setBounds(30, 390, 60, 50);

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/updated.png"))); // NOI18N
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });
        PainelLogin.add(btnAlterar);
        btnAlterar.setBounds(450, 390, 60, 50);

        btnApagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/remove.png"))); // NOI18N
        btnApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApagarActionPerformed(evt);
            }
        });
        PainelLogin.add(btnApagar);
        btnApagar.setBounds(870, 390, 60, 50);

        tb_Login.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Login", "Senha", "Perfil", "Estatus"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tb_Login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_LoginMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_Login);

        PainelLogin.add(jScrollPane1);
        jScrollPane1.setBounds(10, 60, 920, 110);

        txtPesquisar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisarKeyReleased(evt);
            }
        });
        PainelLogin.add(txtPesquisar);
        txtPesquisar.setBounds(500, 10, 390, 40);

        lblPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/magnifying-glass.png"))); // NOI18N
        lblPesquisar.setToolTipText("Pesquisar");
        PainelLogin.add(lblPesquisar);
        lblPesquisar.setBounds(900, 10, 40, 40);

        txtLogin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        PainelLogin.add(txtLogin);
        txtLogin.setBounds(80, 189, 850, 31);

        lblNome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNome.setText("Login");
        PainelLogin.add(lblNome);
        lblNome.setBounds(10, 180, 50, 40);

        getContentPane().add(PainelLogin);
        PainelLogin.setBounds(20, 50, 950, 450);

        setBounds(0, 0, 1000, 560);
    }// </editor-fold>//GEN-END:initComponents

    private void lblLimparMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLimparMouseClicked
        // TODO add your handling code here:
        txtID.setText(null);
        txtLogin.setText(null);
        txtSenha.setText(null);
        txtPerfil.setText(null);
        txtEstatus.setText(null);
        btnAdicionar.setEnabled(true);
        btnAlterar.setEnabled(true);
        btnApagar.setEnabled(true);
    }//GEN-LAST:event_lblLimparMouseClicked

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        // TODO add your handling code here:
        String sql = "insert into tb_login(login, senha, perfil) values(?, ?, ?)";
        try {
            pst = con.prepareStatement(sql);
            pst.setString(1, txtLogin.getText());
            pst.setString(2, txtSenha.getText());
            pst.setString(3, txtPerfil.getText());
            int adicionado = pst.executeUpdate();
            if (txtLogin.getText().isEmpty() || txtSenha.getText().isEmpty() || txtPerfil.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Insira todos os Campos!", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            } else {
                if (adicionado > 0) {
                    JOptionPane.showMessageDialog(null, "Login Adicionado Com Sucesso!", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                    txtID.setText(null);
                    txtLogin.setText(null);
                    txtSenha.setText(null);
                    txtPerfil.setText(null);
                    txtEstatus.setText(null);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Falha na Comunicação com o Banco de Dados\n" + e, "Aviso", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        // TODO add your handling code here:
        String sql = "update tb_user set nome_user = ?, morada_user = ?, telefone_user = ?, email_user = ?, perfil_user = ?, estatus = ? where id_user = ?";
        try {
            pst = con.prepareStatement(sql);
            pst.setString(1, txtLogin.getText());
            pst.setString(2, txtSenha.getText());
            pst.setString(3, txtPerfil.getText());
            pst.setString(4, txtID.getText());
            btnAdicionar.setEnabled(false);
            int alterado = pst.executeUpdate();
            if (txtID.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Insira o ID do Usuário", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            } else {
                if (alterado > 0) {
                    JOptionPane.showMessageDialog(null, "Login Alterado Com Sucesso!", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                    txtID.setText(null);
                    txtLogin.setText(null);
                    txtSenha.setText(null);
                    txtPerfil.setText(null);
                    txtEstatus.setText(null);
                    btnAdicionar.setEnabled(true);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Falha na Comunicação com o Banco de Dados\n" + e, "Aviso", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApagarActionPerformed
        // TODO add your handling code here:
        int apagar = JOptionPane.showConfirmDialog(null, "Deseja Apagar este Usuário?", "Aviso", JOptionPane.YES_NO_OPTION);
        if (apagar == JOptionPane.YES_OPTION) {
            String sql = "delete from tb_login where id_login = ?";
            try {
                pst = con.prepareStatement(sql);
                pst.setString(1, txtID.getText());
                int apagado = pst.executeUpdate();
                if (apagado > 0) {
                    JOptionPane.showMessageDialog(null, "Usuário Apagado com Sucesso!", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                    txtID.setText(null);
                    txtLogin.setText(null);
                    txtSenha.setText(null);
                    txtPerfil.setText(null);
                    txtEstatus.setText(null);
                    btnAdicionar.setEnabled(true);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Falha na Comunicação com o Banco de Dados\n" + e, "Aviso", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnApagarActionPerformed

    private void txtPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarKeyReleased
        // TODO add your handling code here:
        String sql = "select id_login as ID, Login as Login, senha as Senha, perfil as Perfil, estatus as Estatus from tb_login where login like ?";
        try {
            pst = con.prepareStatement(sql);
            pst.setString(1, txtPesquisar.getText() + "%");
            rs = pst.executeQuery();
            tb_Login.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Falha na Comunicação com o Banco de Dados\n" + e, "Aviso", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_txtPesquisarKeyReleased

    private void tb_LoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_LoginMouseClicked
        // TODO add your handling code here:
        int setar = tb_Login.getSelectedRow();
        txtID.setText(tb_Login.getModel().getValueAt(setar, 0).toString());
        txtLogin.setText(tb_Login.getModel().getValueAt(setar, 1).toString());
        txtSenha.setText(tb_Login.getModel().getValueAt(setar, 2).toString());
        txtPerfil.setText(tb_Login.getModel().getValueAt(setar, 3).toString());
        txtEstatus.setText(tb_Login.getModel().getValueAt(setar, 4).toString());
        btnAdicionar.setEnabled(false);
    }//GEN-LAST:event_tb_LoginMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelLogin;
    private javax.swing.JButton btnAdicionar;
    public static javax.swing.JButton btnAlterar;
    public static javax.swing.JButton btnApagar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEstatus;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblLimpar;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblPerfil;
    private javax.swing.JLabel lblPesquisar;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JTable tb_Login;
    private javax.swing.JTextField txtEstatus;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JTextField txtPerfil;
    private javax.swing.JTextField txtPesquisar;
    private javax.swing.JTextField txtSenha;
    // End of variables declaration//GEN-END:variables
}
