/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formulários;

import java.sql.*;
import javax.swing.*;
import Classes.*;
import java.text.*;
import java.util.Date;
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.view.*;

/**
 *
 * @author Mr. Wanny
 */
public class FormularioPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FormularioPrincipal
     */
    public FormularioPrincipal() {
        initComponents();
        con = SQL.connect();
    }

    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelPrincipal = new javax.swing.JPanel();
        lblLogotipo = new javax.swing.JLabel();
        PainelFerramentas = new javax.swing.JPanel();
        lblData = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblEstatus = new javax.swing.JLabel();
        MenuPrincipal = new javax.swing.JMenuBar();
        Menu = new javax.swing.JMenu();
        MenuCadastrar = new javax.swing.JMenu();
        MenuCadastrarCliente = new javax.swing.JMenuItem();
        MenuCadastrarUsuario = new javax.swing.JMenuItem();
        MenuCadastroTecnico = new javax.swing.JMenuItem();
        MenuCadastroLogin = new javax.swing.JMenuItem();
        MenuBackUp = new javax.swing.JMenuItem();
        MenuServico = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        MenuTerminarSessao = new javax.swing.JMenuItem();
        MenuRelatorio = new javax.swing.JMenu();
        MenuRelatoroServico = new javax.swing.JMenuItem();
        MenuRelatorioCliente = new javax.swing.JMenuItem();
        MenuRelatorioTecnico = new javax.swing.JMenuItem();
        MenuRelatorioLogin = new javax.swing.JMenuItem();
        MenuAjuda = new javax.swing.JMenu();
        MenuAjudaAtualizacoes = new javax.swing.JMenuItem();
        MenuAjudaSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Principal");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        PainelPrincipal.setBackground(new java.awt.Color(204, 204, 204));
        PainelPrincipal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        PainelPrincipal.setLayout(null);
        getContentPane().add(PainelPrincipal);
        PainelPrincipal.setBounds(20, 100, 1000, 560);

        lblLogotipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Gingue Tech 2.0.png"))); // NOI18N
        getContentPane().add(lblLogotipo);
        lblLogotipo.setBounds(310, 20, 340, 80);

        PainelFerramentas.setBackground(new java.awt.Color(255, 255, 255));
        PainelFerramentas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        PainelFerramentas.setLayout(null);

        lblData.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblData.setText("Data");
        PainelFerramentas.add(lblData);
        lblData.setBounds(10, 630, 270, 32);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Estatus:");
        PainelFerramentas.add(jLabel1);
        jLabel1.setBounds(10, 590, 90, 32);

        lblEstatus.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblEstatus.setText("Ativo");
        PainelFerramentas.add(lblEstatus);
        lblEstatus.setBounds(100, 590, 150, 32);

        getContentPane().add(PainelFerramentas);
        PainelFerramentas.setBounds(1040, -10, 300, 670);

        MenuPrincipal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        Menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/windows.png"))); // NOI18N
        Menu.setText("Menu");
        Menu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        MenuCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/adicionar-ficheiro.png"))); // NOI18N
        MenuCadastrar.setText("Cadastrar");
        MenuCadastrar.setToolTipText("Cadastrar");
        MenuCadastrar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        MenuCadastrarCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        MenuCadastrarCliente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        MenuCadastrarCliente.setText("Clientes");
        MenuCadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCadastrarClienteActionPerformed(evt);
            }
        });
        MenuCadastrar.add(MenuCadastrarCliente);

        MenuCadastrarUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        MenuCadastrarUsuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        MenuCadastrarUsuario.setText("Usuários");
        MenuCadastrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCadastrarUsuarioActionPerformed(evt);
            }
        });
        MenuCadastrar.add(MenuCadastrarUsuario);

        MenuCadastroTecnico.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        MenuCadastroTecnico.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        MenuCadastroTecnico.setText("Técnico");
        MenuCadastroTecnico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCadastroTecnicoActionPerformed(evt);
            }
        });
        MenuCadastrar.add(MenuCadastroTecnico);

        MenuCadastroLogin.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        MenuCadastroLogin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        MenuCadastroLogin.setText("Login");
        MenuCadastroLogin.setToolTipText("Login");
        MenuCadastroLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCadastroLoginActionPerformed(evt);
            }
        });
        MenuCadastrar.add(MenuCadastroLogin);

        Menu.add(MenuCadastrar);

        MenuBackUp.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        MenuBackUp.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        MenuBackUp.setText("Back Up");
        Menu.add(MenuBackUp);

        MenuServico.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        MenuServico.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        MenuServico.setText("Serviços");
        MenuServico.setToolTipText("Serviços");
        MenuServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuServicoActionPerformed(evt);
            }
        });
        Menu.add(MenuServico);
        Menu.add(jSeparator1);

        MenuTerminarSessao.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        MenuTerminarSessao.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        MenuTerminarSessao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/exit.png"))); // NOI18N
        MenuTerminarSessao.setText("Log Out");
        MenuTerminarSessao.setToolTipText("Log Out");
        MenuTerminarSessao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuTerminarSessaoActionPerformed(evt);
            }
        });
        Menu.add(MenuTerminarSessao);

        MenuPrincipal.add(Menu);

        MenuRelatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/report.png"))); // NOI18N
        MenuRelatorio.setText("Relatórios");
        MenuRelatorio.setToolTipText("Relatórios");
        MenuRelatorio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        MenuRelatoroServico.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK));
        MenuRelatoroServico.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        MenuRelatoroServico.setText("Serviços");
        MenuRelatorio.add(MenuRelatoroServico);

        MenuRelatorioCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK));
        MenuRelatorioCliente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        MenuRelatorioCliente.setText("Clientes");
        MenuRelatorioCliente.setToolTipText("Clientes");
        MenuRelatorioCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuRelatorioClienteActionPerformed(evt);
            }
        });
        MenuRelatorio.add(MenuRelatorioCliente);

        MenuRelatorioTecnico.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.SHIFT_MASK));
        MenuRelatorioTecnico.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        MenuRelatorioTecnico.setText("Técnicos");
        MenuRelatorioTecnico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuRelatorioTecnicoActionPerformed(evt);
            }
        });
        MenuRelatorio.add(MenuRelatorioTecnico);

        MenuRelatorioLogin.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.SHIFT_MASK));
        MenuRelatorioLogin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        MenuRelatorioLogin.setText("Login");
        MenuRelatorioLogin.setToolTipText("Login");
        MenuRelatorioLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuRelatorioLoginActionPerformed(evt);
            }
        });
        MenuRelatorio.add(MenuRelatorioLogin);

        MenuPrincipal.add(MenuRelatorio);

        MenuAjuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/em-formacao (1).png"))); // NOI18N
        MenuAjuda.setText("Ajuda");
        MenuAjuda.setToolTipText("Ajuda");
        MenuAjuda.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        MenuAjudaAtualizacoes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        MenuAjudaAtualizacoes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        MenuAjudaAtualizacoes.setText("Verificar Atualizações");
        MenuAjudaAtualizacoes.setToolTipText("Verficar Atualizações");
        MenuAjuda.add(MenuAjudaAtualizacoes);

        MenuAjudaSobre.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        MenuAjudaSobre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        MenuAjudaSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/info.png"))); // NOI18N
        MenuAjudaSobre.setText("Sobre");
        MenuAjudaSobre.setToolTipText("Sobre");
        MenuAjudaSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuAjudaSobreActionPerformed(evt);
            }
        });
        MenuAjuda.add(MenuAjudaSobre);

        MenuPrincipal.add(MenuAjuda);

        setJMenuBar(MenuPrincipal);

        setSize(new java.awt.Dimension(1346, 748));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MenuCadastrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCadastrarUsuarioActionPerformed
        // TODO add your handling code here:
        try {
            FormularioCadastrarUsuario usuario = new FormularioCadastrarUsuario();
            usuario.setVisible(true);
            PainelPrincipal.add(usuario);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Falha na Comunicação com o Banco de Dados\n" + e, "Aviso", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_MenuCadastrarUsuarioActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        Date data = new Date();
        DateFormat formatador = DateFormat.getDateInstance(DateFormat.LONG);
        lblData.setText(formatador.format(data));
    }//GEN-LAST:event_formWindowActivated

    private void MenuCadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCadastrarClienteActionPerformed
        // TODO add your handling code here:
        try {
            FormularioCadastrarClientes cliente = new FormularioCadastrarClientes();
            cliente.setVisible(true);
            PainelPrincipal.add(cliente);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Falha na Comunicação com o Banco de Dados\n" + e, "Aviso", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_MenuCadastrarClienteActionPerformed

    private void MenuAjudaSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuAjudaSobreActionPerformed
        // TODO add your handling code here:
        FormularioSobre sobre = new FormularioSobre();
        sobre.setVisible(true);
    }//GEN-LAST:event_MenuAjudaSobreActionPerformed

    private void MenuTerminarSessaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuTerminarSessaoActionPerformed
        // TODO add your handling code here:
        int terminar = JOptionPane.showConfirmDialog(null, "Deseja Terminar a Sessão?", "Aviso", JOptionPane.YES_NO_OPTION);
        if (terminar == JOptionPane.YES_OPTION) {
            try {
                JOptionPane.showMessageDialog(null, "A Sessão será encerrada em alguns segundos", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                for (int i = 0; i < 101; i += 50) {
                    Thread.sleep(300);
                }
                this.dispose();
                JOptionPane.showMessageDialog(null, "Sessão Encerrada!", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                FormularioLogin log = new FormularioLogin();
                log.setVisible(true);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Falha na Comunicação com o Banco de Dados\n" + e, "Aviso", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_MenuTerminarSessaoActionPerformed

    private void MenuCadastroTecnicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCadastroTecnicoActionPerformed
        // TODO add your handling code here:
        FormularioTecnico tecnico = new FormularioTecnico();
        tecnico.setVisible(true);
        PainelPrincipal.add(tecnico);
    }//GEN-LAST:event_MenuCadastroTecnicoActionPerformed

    private void MenuRelatorioClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuRelatorioClienteActionPerformed
        // TODO add your handling code here:
        int confirmar = JOptionPane.showConfirmDialog(null, "Deseja Imprimir a Lista de Clientes?", "Aviso", JOptionPane.YES_NO_OPTION);
        if (confirmar == JOptionPane.YES_OPTION) {
            try {
                JasperPrint print = JasperFillManager.fillReport("C:\\Users\\Mr. Wanny\\Documents\\NetBeansProjects\\Empresa Gingue Tech\\src\\Relatórios\\RelatorioCliente.jasper", null, con);
                JasperViewer.viewReport(print, false);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Falha na Comunicação com o Banco de Dados\n" + e, "Aviso", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_MenuRelatorioClienteActionPerformed

    private void MenuRelatorioTecnicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuRelatorioTecnicoActionPerformed
        // TODO add your handling code here:
        int confirmar = JOptionPane.showConfirmDialog(null, "Deseja Imprimir a Lista de Técnicos?", "Aviso", JOptionPane.YES_NO_OPTION);
        if (confirmar == JOptionPane.YES_OPTION) {
            try {
                JasperPrint print = JasperFillManager.fillReport("C:\\Users\\Mr. Wanny\\Documents\\NetBeansProjects\\Empresa Gingue Tech\\src\\Relatórios\\RelatorioTecnico.jasper", null, con);
                JasperViewer.viewReport(print, false);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Falha na Comunicação com o Banco de Dados\n" + e, "Aviso", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_MenuRelatorioTecnicoActionPerformed

    private void MenuRelatorioLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuRelatorioLoginActionPerformed
        // TODO add your handling code here:
        int confirmar = JOptionPane.showConfirmDialog(null, "Deseja Imprimir a Lista de Técnicos?", "Aviso", JOptionPane.YES_NO_OPTION);
        if (confirmar == JOptionPane.YES_OPTION) {
            try {
                JasperPrint print = JasperFillManager.fillReport("C:\\Users\\Mr. Wanny\\Documents\\NetBeansProjects\\Empresa Gingue Tech\\src\\Relatórios\\RelatorioLogin.jasper", null, con);
                JasperViewer.viewReport(print, false);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Falha na Comunicação com o Banco de Dados\n" + e, "Aviso", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_MenuRelatorioLoginActionPerformed

    private void MenuCadastroLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCadastroLoginActionPerformed
        // TODO add your handling code here:
        FormularioCadastroLogin log = new FormularioCadastroLogin();
        log.setVisible(true);
        PainelPrincipal.add(log);
    }//GEN-LAST:event_MenuCadastroLoginActionPerformed

    private void MenuServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuServicoActionPerformed
        // TODO add your handling code here:
        FormularioServico serv = new FormularioServico();
        serv.setVisible(true);
        PainelPrincipal.add(serv);
    }//GEN-LAST:event_MenuServicoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JMenu Menu;
    public static javax.swing.JMenu MenuAjuda;
    public static javax.swing.JMenuItem MenuAjudaAtualizacoes;
    public static javax.swing.JMenuItem MenuAjudaSobre;
    public static javax.swing.JMenuItem MenuBackUp;
    public static javax.swing.JMenu MenuCadastrar;
    public static javax.swing.JMenuItem MenuCadastrarCliente;
    public static javax.swing.JMenuItem MenuCadastrarUsuario;
    private javax.swing.JMenuItem MenuCadastroLogin;
    public static javax.swing.JMenuItem MenuCadastroTecnico;
    private javax.swing.JMenuBar MenuPrincipal;
    public static javax.swing.JMenu MenuRelatorio;
    public static javax.swing.JMenuItem MenuRelatorioCliente;
    private javax.swing.JMenuItem MenuRelatorioLogin;
    public static javax.swing.JMenuItem MenuRelatorioTecnico;
    public static javax.swing.JMenuItem MenuRelatoroServico;
    public static javax.swing.JMenuItem MenuServico;
    public static javax.swing.JMenuItem MenuTerminarSessao;
    private javax.swing.JPanel PainelFerramentas;
    private javax.swing.JPanel PainelPrincipal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel lblData;
    public static javax.swing.JLabel lblEstatus;
    private javax.swing.JLabel lblLogotipo;
    // End of variables declaration//GEN-END:variables
}
