/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formulários;

import java.sql.*;
import javax.swing.*;
import Classes.SQL;
import net.proteanit.sql.DbUtils;
import javax.swing.filechooser.*;

/**
 *
 * @author Mr. Wanny
 */
public class FormularioTecnico extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormularioTecnico
     */
    public FormularioTecnico() {
        initComponents();
        con = SQL.connect();
    }

    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    JFileChooser chooser;
    FileNameExtensionFilter filtro;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        PainelServico = new javax.swing.JPanel();
        lblID = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtPesquisar = new javax.swing.JTextField();
        lblPesquisar = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_Tecnico = new javax.swing.JTable();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblTelefone = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        btnAdicionar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnApagar = new javax.swing.JButton();
        lblEstatus = new javax.swing.JLabel();
        txtEstatus = new javax.swing.JTextField();
        lblLimpar = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Cadastrar Tecnico");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(340, 0, 290, 48);

        PainelServico.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        PainelServico.setLayout(null);

        lblID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblID.setText("ID");
        PainelServico.add(lblID);
        lblID.setBounds(10, 10, 30, 40);

        txtID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtID.setEnabled(false);
        PainelServico.add(txtID);
        txtID.setBounds(40, 10, 70, 40);

        txtPesquisar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisarKeyReleased(evt);
            }
        });
        PainelServico.add(txtPesquisar);
        txtPesquisar.setBounds(500, 10, 390, 40);

        lblPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/loupe.png"))); // NOI18N
        PainelServico.add(lblPesquisar);
        lblPesquisar.setBounds(900, 10, 34, 40);

        tb_Tecnico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Telefone", "Email", "Estatus"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tb_Tecnico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_TecnicoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tb_Tecnico);

        PainelServico.add(jScrollPane2);
        jScrollPane2.setBounds(10, 60, 930, 160);

        lblNome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNome.setText("Nome");
        PainelServico.add(lblNome);
        lblNome.setBounds(10, 230, 60, 40);

        txtNome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        PainelServico.add(txtNome);
        txtNome.setBounds(80, 230, 860, 40);

        lblTelefone.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTelefone.setText("Telefone");
        PainelServico.add(lblTelefone);
        lblTelefone.setBounds(10, 280, 70, 40);

        txtTelefone.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        PainelServico.add(txtTelefone);
        txtTelefone.setBounds(80, 280, 860, 40);

        lblEmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblEmail.setText("E - Mail");
        PainelServico.add(lblEmail);
        lblEmail.setBounds(10, 330, 70, 40);

        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        PainelServico.add(txtEmail);
        txtEmail.setBounds(80, 330, 390, 40);

        btnAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/add.png"))); // NOI18N
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });
        PainelServico.add(btnAdicionar);
        btnAdicionar.setBounds(10, 390, 50, 50);

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/updated.png"))); // NOI18N
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });
        PainelServico.add(btnAlterar);
        btnAlterar.setBounds(470, 390, 60, 50);

        btnApagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/remove.png"))); // NOI18N
        btnApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApagarActionPerformed(evt);
            }
        });
        PainelServico.add(btnApagar);
        btnApagar.setBounds(880, 390, 57, 50);

        lblEstatus.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblEstatus.setText("Estatus");
        PainelServico.add(lblEstatus);
        lblEstatus.setBounds(480, 330, 60, 40);

        txtEstatus.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        PainelServico.add(txtEstatus);
        txtEstatus.setBounds(540, 330, 400, 40);

        getContentPane().add(PainelServico);
        PainelServico.setBounds(20, 50, 950, 450);

        lblLimpar.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblLimpar.setText("X");
        lblLimpar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLimparMouseClicked(evt);
            }
        });
        getContentPane().add(lblLimpar);
        lblLimpar.setBounds(940, 0, 30, 48);

        setBounds(0, 0, 1000, 560);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        // TODO add your handling code here:
        String sql = "insert into tb_tecnico(nome_tecnico, telefone_tecnico, email_tecnico, estatus_tecnico) values(?, ?, ?, ?)";
        try {
            pst = con.prepareStatement(sql);
            pst.setString(1, txtNome.getText());
            pst.setString(2, txtTelefone.getText());
            pst.setString(3, txtEmail.getText());
            pst.setString(4, txtEstatus.getText());
            int adicionado = pst.executeUpdate();
            if (adicionado > 0) {
                JOptionPane.showMessageDialog(null, "Técnico Adicionado Com Sucesso!", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                txtID.setText(null);
                txtNome.setText(null);
                txtTelefone.setText(null);
                txtEmail.setText(null);
                txtEstatus.setText(null);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Falha na Comunicação com o Banco de Dados\n" + e, "Aviso", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApagarActionPerformed
        // TODO add your handling code here:
        int apagar = JOptionPane.showConfirmDialog(null, "Deseja Apagar este Cliente?", "Aviso", JOptionPane.YES_NO_OPTION);
        if (apagar == JOptionPane.YES_OPTION) {
            String sql = "delete from tb_cliente where id_tecnico = ?";
            try {
                pst = con.prepareStatement(sql);
                pst.setString(1, txtID.getText());
                int apagado = pst.executeUpdate();
                if (txtID.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Insira o ID do Técnico", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    if (apagado > 0) {
                        JOptionPane.showMessageDialog(null, "Técnico Apagado com Sucesso!", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                        txtID.setText(null);
                        txtNome.setText(null);
                        txtTelefone.setText(null);
                        txtEmail.setText(null);
                        txtEstatus.setText(null);
                        btnAdicionar.setEnabled(true);
                        btnAlterar.setEnabled(true);
                        btnApagar.setEnabled(true);
                    }
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Falha na Comunicação com o Banco de Dados\n" + e, "Aviso", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnApagarActionPerformed

    private void tb_TecnicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_TecnicoMouseClicked
        // TODO add your handling code here:
        int setar = tb_Tecnico.getSelectedRow();
        txtID.setText(tb_Tecnico.getModel().getValueAt(setar, 0).toString());
        txtNome.setText(tb_Tecnico.getModel().getValueAt(setar, 1).toString());
        txtTelefone.setText(tb_Tecnico.getModel().getValueAt(setar, 2).toString());
        txtEmail.setText(tb_Tecnico.getModel().getValueAt(setar, 3).toString());
        txtEstatus.setText(tb_Tecnico.getModel().getValueAt(setar, 4).toString());
        btnAdicionar.setEnabled(false);
    }//GEN-LAST:event_tb_TecnicoMouseClicked

    private void txtPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarKeyReleased
        // TODO add your handling code here:
        String sql = "select id_tecnico as ID, nome_tecnico as Nome, telefone_tecnico as Telefone, email_tecnico as Email, estatus_tecnico as Estatus from tb_tecnico where nome_tecnico like ?";
        try {
            pst = con.prepareStatement(sql);
            pst.setString(1, txtPesquisar.getText() + "%");
            rs = pst.executeQuery();
            tb_Tecnico.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Falha na Comunicação com o Banco de Dados\n" + e, "Aviso", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_txtPesquisarKeyReleased

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        // TODO add your handling code here:
        String sql = "update tb_tecnico set nome_tecnico = ?, telefone_tecnico = ?, email_tecnico = ?, estatus_tecnico = ? where id_tecnico = ?";
        try {
            pst = con.prepareStatement(sql);
            pst.setString(1, txtNome.getText());
            pst.setString(2, txtTelefone.getText());
            pst.setString(3, txtEmail.getText());
            pst.setString(4, txtEstatus.getText());
            pst.setString(5, txtID.getText());
            int alterado = pst.executeUpdate();
            if (alterado > 0) {
                JOptionPane.showMessageDialog(null, "Dados do Técnico Alterados com Sucesso!", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                txtID.setText(null);
                txtNome.setText(null);
                txtTelefone.setText(null);
                txtEmail.setText(null);
                txtEstatus.setText(null);
                btnAdicionar.setEnabled(true);
                btnAlterar.setEnabled(true);
                btnApagar.setEnabled(true);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Falha na Comunicação com o Banco de Dados\n" + e, "Aviso", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void lblLimparMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLimparMouseClicked
        // TODO add your handling code here:
        txtID.setText(null);
        txtNome.setText(null);
        txtTelefone.setText(null);
        txtEmail.setText(null);
        txtEstatus.setText(null);
        btnAdicionar.setEnabled(true);
        btnAlterar.setEnabled(true);
        btnApagar.setEnabled(true);
    }//GEN-LAST:event_lblLimparMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelServico;
    private javax.swing.JButton btnAdicionar;
    public static javax.swing.JButton btnAlterar;
    public static javax.swing.JButton btnApagar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEstatus;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblLimpar;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblPesquisar;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JTable tb_Tecnico;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEstatus;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPesquisar;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
