/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formulários;

import java.sql.*;
import javax.swing.*;
import Classes.*;
import net.proteanit.sql.DbUtils;
import javax.swing.filechooser.*;

/**
 *
 * @author Mr. Wanny
 */
public class FormularioCadastrarClientes extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormularioCadastrarUsuario
     */
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    JFileChooser chooser;
    FileNameExtensionFilter filtro;

    public FormularioCadastrarClientes() {
        initComponents();
        con = SQL.connect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        PainelCadastroClientes = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_Clientes = new javax.swing.JTable();
        txtPesquisar = new javax.swing.JTextField();
        lblID = new javax.swing.JLabel();
        lblPesquisar = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        txtMorada = new javax.swing.JTextField();
        lblIMorada = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JTextField();
        lblTelefone = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblIEmail = new javax.swing.JLabel();
        txtEstatus = new javax.swing.JTextField();
        lblEstatus = new javax.swing.JLabel();
        btnAdicionar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnApagar = new javax.swing.JButton();
        lblLimpar = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Clientes");
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Cadastro de Clientes");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(340, 0, 340, 48);

        PainelCadastroClientes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        PainelCadastroClientes.setLayout(null);

        tb_Clientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Morada", "Telefone", "Email", "Estatus"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_Clientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_ClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_Clientes);

        PainelCadastroClientes.add(jScrollPane1);
        jScrollPane1.setBounds(10, 60, 930, 160);

        txtPesquisar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisarKeyReleased(evt);
            }
        });
        PainelCadastroClientes.add(txtPesquisar);
        txtPesquisar.setBounds(500, 10, 390, 40);

        lblID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblID.setText("ID");
        PainelCadastroClientes.add(lblID);
        lblID.setBounds(10, 10, 30, 40);

        lblPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/magnifying-glass.png"))); // NOI18N
        lblPesquisar.setToolTipText("Pesquisar");
        PainelCadastroClientes.add(lblPesquisar);
        lblPesquisar.setBounds(900, 10, 40, 40);

        txtID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtID.setEnabled(false);
        PainelCadastroClientes.add(txtID);
        txtID.setBounds(40, 10, 60, 40);

        txtNome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        PainelCadastroClientes.add(txtNome);
        txtNome.setBounds(70, 230, 390, 40);

        lblNome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNome.setText("Nome");
        PainelCadastroClientes.add(lblNome);
        lblNome.setBounds(10, 230, 50, 40);

        txtMorada.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        PainelCadastroClientes.add(txtMorada);
        txtMorada.setBounds(570, 230, 370, 40);

        lblIMorada.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblIMorada.setText("Morada");
        PainelCadastroClientes.add(lblIMorada);
        lblIMorada.setBounds(500, 230, 70, 40);

        txtTelefone.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        PainelCadastroClientes.add(txtTelefone);
        txtTelefone.setBounds(90, 280, 370, 40);

        lblTelefone.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTelefone.setText("Telefone");
        PainelCadastroClientes.add(lblTelefone);
        lblTelefone.setBounds(10, 280, 70, 40);

        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        PainelCadastroClientes.add(txtEmail);
        txtEmail.setBounds(580, 280, 360, 40);

        lblIEmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblIEmail.setText("E - mail");
        PainelCadastroClientes.add(lblIEmail);
        lblIEmail.setBounds(500, 280, 60, 40);

        txtEstatus.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        PainelCadastroClientes.add(txtEstatus);
        txtEstatus.setBounds(80, 330, 860, 40);

        lblEstatus.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblEstatus.setText("Estatus");
        PainelCadastroClientes.add(lblEstatus);
        lblEstatus.setBounds(10, 330, 60, 40);

        btnAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/add.png"))); // NOI18N
        btnAdicionar.setToolTipText("Adicionar");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });
        PainelCadastroClientes.add(btnAdicionar);
        btnAdicionar.setBounds(10, 380, 50, 50);

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/updated.png"))); // NOI18N
        btnAlterar.setToolTipText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });
        PainelCadastroClientes.add(btnAlterar);
        btnAlterar.setBounds(470, 380, 60, 50);

        btnApagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/remove.png"))); // NOI18N
        btnApagar.setToolTipText("Apagar");
        btnApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApagarActionPerformed(evt);
            }
        });
        PainelCadastroClientes.add(btnApagar);
        btnApagar.setBounds(880, 380, 57, 50);

        getContentPane().add(PainelCadastroClientes);
        PainelCadastroClientes.setBounds(20, 50, 950, 450);

        lblLimpar.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblLimpar.setText("X");
        lblLimpar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLimparMouseClicked(evt);
            }
        });
        getContentPane().add(lblLimpar);
        lblLimpar.setBounds(930, 0, 30, 48);

        setBounds(0, 0, 1000, 560);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        // TODO add your handling code here:
        String sql = "insert into tb_cliente(nome_cli, morada_cli, telefone_cli, email_cli, estatus_cli) values(?, ?, ?, ?, ?)";
        try {
            pst = con.prepareStatement(sql);
            pst.setString(1, txtNome.getText());
            pst.setString(2, txtMorada.getText());
            pst.setString(3, txtTelefone.getText());
            pst.setString(4, txtEmail.getText());
            pst.setString(5, txtEstatus.getText());
            int adicionado = pst.executeUpdate();
            if (adicionado > 0) {
                JOptionPane.showMessageDialog(null, "Cliente Adicionado Com Sucesso!", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                txtNome.setText(null);
                txtMorada.setText(null);
                txtTelefone.setText(null);
                txtEmail.setText(null);
                txtEstatus.setText(null);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Falha na Comunicação com o Banco de Dados\n" + e, "Aviso", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void txtPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarKeyReleased
        // TODO add your handling code here:
        String sql = "select id_cli as ID, nome_cli AS Nome, morada_cli as Morada, telefone_cli as Telefone, email_cli as Email, estatus_cli as Estatus from tb_cliente where nome_cli like ?";
        try {
            pst = con.prepareStatement(sql);
            pst.setString(1, txtPesquisar.getText() + "%");
            rs = pst.executeQuery();
            tb_Clientes.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Falha na Comunicação com o Banco de Dados\n" + e, "Aviso", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_txtPesquisarKeyReleased

    private void tb_ClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_ClientesMouseClicked
        // TODO add your handling code here:
        int setar = tb_Clientes.getSelectedRow();
        txtID.setText(tb_Clientes.getModel().getValueAt(setar, 0).toString());
        txtNome.setText(tb_Clientes.getModel().getValueAt(setar, 1).toString());
        txtMorada.setText(tb_Clientes.getModel().getValueAt(setar, 2).toString());
        txtTelefone.setText(tb_Clientes.getModel().getValueAt(setar, 3).toString());
        txtEmail.setText(tb_Clientes.getModel().getValueAt(setar, 4).toString());
        txtEstatus.setText(tb_Clientes.getModel().getValueAt(setar, 5).toString());
        btnAdicionar.setEnabled(false);
    }//GEN-LAST:event_tb_ClientesMouseClicked

    private void btnApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApagarActionPerformed
        // TODO add your handling code here:
        int apagar = JOptionPane.showConfirmDialog(null, "Deseja Apagar este Cliente?", "Aviso", JOptionPane.YES_NO_OPTION);
        if (apagar == JOptionPane.YES_OPTION) {
            String sql = "delete from tb_cliente where id_cli = ?";
            try {
                pst = con.prepareStatement(sql);
                pst.setString(1, txtID.getText());
                int apagado = pst.executeUpdate();
                if (txtID.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Insira o ID do Cliente", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    if (apagado > 0) {
                        JOptionPane.showMessageDialog(null, "Cliente Apagado com Sucesso!", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                        txtNome.setText(null);
                        txtMorada.setText(null);
                        txtTelefone.setText(null);
                        txtEmail.setText(null);
                        txtEstatus.setText(null);
                        btnAdicionar.setEnabled(true);
                    }
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Falha na Comunicação com o Banco de Dados\n" + e, "Aviso", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnApagarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        // TODO add your handling code here:
        String sql = "update tb_cliente set nome_cli = ?, morada_cli = ?, telefone_cli = ?, email_cli = ?, estatus_cli = ? where id_cli = ?";
        try {
            pst = con.prepareStatement(sql);
            pst.setString(1, txtNome.getText());
            pst.setString(2, txtMorada.getText());
            pst.setString(3, txtTelefone.getText());
            pst.setString(4, txtEmail.getText());
            pst.setString(5, txtEstatus.getText());
            pst.setString(6, txtID.getText());
            int alterado = pst.executeUpdate();
            if (alterado > 0) {
                JOptionPane.showMessageDialog(null, "Dados do Cliente Alterados com Sucesso!", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                txtNome.setText(null);
                txtMorada.setText(null);
                txtTelefone.setText(null);
                txtEmail.setText(null);
                txtEstatus.setText(null);
                btnAdicionar.setEnabled(true);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Falha na Comunicação com o Banco de Dados\n" + e, "Aviso", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void lblLimparMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLimparMouseClicked
        // TODO add your handling code here:
        txtID.setText(null);
        txtNome.setText(null);
        txtMorada.setText(null);
        txtTelefone.setText(null);
        txtEmail.setText(null);
        txtEstatus.setText(null);
        btnAdicionar.setEnabled(true);
        btnAlterar.setEnabled(true);
        btnApagar.setEnabled(true);
    }//GEN-LAST:event_lblLimparMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelCadastroClientes;
    private javax.swing.JButton btnAdicionar;
    public static javax.swing.JButton btnAlterar;
    public static javax.swing.JButton btnApagar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEstatus;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblIEmail;
    private javax.swing.JLabel lblIMorada;
    private javax.swing.JLabel lblLimpar;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblPesquisar;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JTable tb_Clientes;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEstatus;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtMorada;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPesquisar;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
